<?php
/**
 * AI-NOC — Configuration File (Sample)
 * File: /config/config.sample.php
 * Copy to config.php and edit values after install.
 */

declare(strict_types=1);

return [
    // Application key — 32 random bytes, base64-encoded. Generated by installer.
    'APP_KEY' => '',

    // Base URL of the application (no trailing slash)
    'BASE_URL' => 'https://your-domain.com/ai-noc',

    // Database driver: 'sqlite' or 'mysql'
    'DB_DRIVER' => 'sqlite',

    // SQLite path (relative to project root)
    'DB_SQLITE_PATH' => __DIR__ . '/../data/ai-noc.sqlite',

    // MySQL settings (only used if DB_DRIVER = 'mysql')
    'DB_MYSQL_HOST' => '127.0.0.1',
    'DB_MYSQL_PORT' => 3306,
    'DB_MYSQL_NAME' => 'ai_noc',
    'DB_MYSQL_USER' => '',
    'DB_MYSQL_PASS' => '',

    // Session settings
    'SESSION_LIFETIME' => 3600,       // 1 hour
    'SESSION_NAME'     => 'ainoc_sid',

    // Rate limiting
    'LOGIN_MAX_ATTEMPTS'  => 5,
    'LOGIN_LOCKOUT_MINS'  => 15,

    // Timezone
    'TIMEZONE' => 'Australia/Hobart',

    // Logging
    'LOG_LEVEL' => 'info', // debug, info, warning, error

    // Public access (allow unauthenticated dashboard view)
    'PUBLIC_DASHBOARD' => true,

    // status.json endpoint
    'PUBLIC_STATUS_JSON' => true,

    // Check defaults
    'DEFAULT_CHECK_INTERVAL' => 300,   // seconds
    'DEFAULT_TIMEOUT_MS'     => 10000, // 10s

    // Incident engine
    'INCIDENT_CONFIRM_CHECKS' => 3,   // N checks before creating incident
    'INCIDENT_RESOLVE_CHECKS' => 3,   // M checks before resolving

    // Data retention (days)
    'RETENTION_RAW_CHECKS' => 90,
    'RETENTION_INCIDENTS'  => 365,

    // SMTP (can also be stored encrypted in DB settings)
    'SMTP_ENABLED'  => false,
    'SMTP_HOST'     => '',
    'SMTP_PORT'     => 587,
    'SMTP_USER'     => '',
    'SMTP_PASS'     => '',
    'SMTP_FROM'     => 'noc@your-domain.com',
    'SMTP_FROM_NAME'=> 'AI-NOC',
    'SMTP_ENCRYPTION'=> 'tls',

    // Webhook (generic POST)
    'WEBHOOK_ENABLED' => false,
    'WEBHOOK_URL'     => '',

    // Daily digest time (24h format, in configured timezone)
    'DIGEST_TIME' => '08:00',

    // Alert cooldown (minutes) — suppress duplicate alerts
    'ALERT_COOLDOWN_MINS' => 30,
];
